import { SchemaType } from '@/components/library';

const jobPostSchema: SchemaType<any> = {
	name: {
		label: 'Job Title',
		type: 'string',
		isRequired: true,
		default: true,
		displayInTable: true,
		sort: true,
	},
	company: {
		label: 'Company',
		type: 'string',
		isRequired: true,
		default: true,
		displayInTable: true,
		sort: true,
	},
	email: { label: 'Email', type: 'string', displayInTable: true },
	category: { label: 'Job Category', type: 'string', displayInTable: true },
	postingDate: {
		label: 'Posting Date',
		type: 'date',

		displayInTable: true,
		sort: true,
	},
	postingMedia: { label: 'Posting Media', type: 'string', displayInTable: true },
	experienceLevel: {
		label: 'Experience Level',
		type: 'select',
		options: [
			{ label: 'Entry Level', value: 'entry-level' },
			{ label: 'Mid Level', value: 'mid-level' },
			{ label: 'Senior Level', value: 'senior-level' },
			{ label: 'Management', value: 'management' },
			{ label: 'Other', value: 'other' },
		],
	},
	educationLevel: {
		label: 'Education Level',
		type: 'select',
		options: [
			{ label: 'High School', value: 'high-school' },
			{ label: 'Diploma', value: 'diploma' },
			{ label: 'Bachelors', value: 'bachelors' },
			{ label: 'Masters', value: 'masters' },
			{ label: 'PhD', value: 'phd' },
			{ label: 'Other', value: 'other' },
		],
	},
	applicationProcess: { label: 'Application Process', type: 'textarea' },
	shift: {
		label: 'Shift',
		type: 'select',
		displayInTable: true,
		options: [
			{ label: 'Morning', value: 'morning' },
			{ label: 'Evening', value: 'evening' },
			{ label: 'Night', value: 'night' },
			{ label: 'Rotational', value: 'rotational' },
			{ label: 'Other', value: 'other' },
		],
	},
	phone: { label: 'Phone', type: 'string' },
	website: { label: 'Website', type: 'string', viewType: 'external-link' },
	address: { label: 'Address', type: 'textarea' },
	city: { label: 'City', type: 'string', displayInTable: true },
	country: { label: 'Country', type: 'string', displayInTable: true, sort: true },
	industry: { label: 'Industry', type: 'string', displayInTable: true, sort: true },
	companyDescription: { label: 'Company Description', type: 'textarea' },
	employmentType: {
		label: 'Employment Type',
		type: 'select',
		isRequired: true,
		displayInTable: true,
		options: [
			{ label: 'Full Time', value: 'full-time' },
			{ label: 'Part Time', value: 'part-time' },
			{ label: 'Contract', value: 'contract' },
			{ label: 'Internship', value: 'internship' },
			{ label: 'Temporary', value: 'temporary' },
			{ label: 'Freelance', value: 'freelance' },
			{ label: 'Other', value: 'other' },
		],
	},
	jobLocationType: {
		label: 'Job Location Type',
		type: 'select',
		isRequired: true,
		displayInTable: true,
		options: [
			{ label: 'Remote', value: 'remote' },
			{ label: 'Onsite', value: 'onsite' },
			{ label: 'Hybrid', value: 'hybrid' },
		],
	},
	jobLocation: { label: 'Job Location', type: 'string', displayInTable: true },
	minSalary: { label: 'Minimum Salary', type: 'number', isRequired: true, displayInTable: true },
	maxSalary: { label: 'Maximum Salary', type: 'number', isRequired: true },
	salaryType: {
		label: 'Salary Type',
		type: 'select',
		options: [
			{ label: 'Hourly', value: 'hourly' },
			{ label: 'Weekly', value: 'weekly' },
			{ label: 'Monthly', value: 'monthly' },
			{ label: 'Yearly', value: 'yearly' },
		],
	},
	salaryCurrency: { label: 'Salary Currency', type: 'string' },
	jobDescription: { label: 'Job Description', type: 'textarea' },
	requirements: { label: 'Requirements', type: 'tag' },
	qualifications: { label: 'Qualifications', type: 'tag' },
	responsibilities: { label: 'Responsibilities', type: 'tag' },
	tags: { label: 'Tags', type: 'tag' },
	noOfOpenings: { label: 'Number of Openings', type: 'number', displayInTable: true },
	applicationUrl: {
		label: 'Application URL',
		type: 'string',
		viewType: 'external-link',
		tableType: 'external-link',
		displayInTable: true,
	},
	companyLogo: { label: 'Company Logo', type: 'image' },
	skills: { label: 'Skills', type: 'tag' },
	benefits: { label: 'Benefits', type: 'tag' },
	addedBy: {
		label: 'Added By',
		type: 'string',
		displayInTable: true,
		sort: true,
		tableKey: 'addedBy.name',
	},
	isActive: { label: 'Active Status', type: 'checkbox', displayInTable: true },
	deadline: { label: 'Deadline', type: 'date', displayInTable: true, sort: true },
	file: { label: 'File', type: 'file' },
	fileUrl: { label: 'File Url', type: 'string', viewType: 'external-link', copy: true },
	status: {
		label: 'Status',
		type: 'select',
		isRequired: true,
		options: [
			{ label: 'Draft', value: 'draft' },
			{ label: 'Published', value: 'published' },
			{ label: 'Open', value: 'open' },
			{ label: 'Paused', value: 'paused' },
			{ label: 'Completed', value: 'completed' },
			{ label: 'Closed', value: 'closed' },
			{ label: 'Archived', value: 'archived' },
			{ label: 'Deleted', value: 'deleted' },
			{ label: 'Expired', value: 'expired' },
		],
	},
};

export default jobPostSchema;
